    <div id="main" role="main" class="container_12">
    	<div id="proyectos" class="grid_8 push_2">
    		<h1>Proyectos</h1>
    		<span class="linea grid_12 pull_2 alpha omega">
    		</span>
    		<div class="flecha inactive" data-dir="izda" id="flechaIzda"></div>
    		<div id="proyectosExt" style="">
    			<div id="proyectosCont">
    				<!-- Autogenerated Projects -->
    				<?php $files = glob("static/img/proyectos/*", GLOB_ONLYDIR);
    				$i = 1;
    				foreach($files as $file) { 	?>
    				<div id="proyecto<?= $i ?>" data-index="<?= $i ?>" class="grid_3 <?php echo (($i == 1 || $i%4 == 1) ? 'alpha' : (($i%4 == 0) ? 'omega' : '')); ?> proyecto">
    					<a href="<?= $file; ?>/ficha.jpg" class="ficha">
    						<img class="proyectoThumb" src="<?= $file; ?>/thumb.jpg"/>
    					</a>
    				</div>
    				<?php $i++; } ?>
    				<!-- END of the projects -->
    			</div>
    		</div>
    		<div class="flecha inactive" data-dir="dcha" id="flechaDcha"></div>
    		<span class="linea baja grid_12 pull_2 alpha omega"></span>
    		<div class="clear"></div>
    		<div id="descripcion" class="grid_12 pull_2">
    		</div>
    		<div id="indice" class="grid_12 pull_2" >
    			<ul></ul>
    		</div>
    	</div>
    </div>
    <div class="clear"></div>